
# air.toml
root = "."
tmp_dir = "tmp"

[build]
# Just plain old `go build`.
cmd = "swag init --parseDependency --parseInternal && go build -o ./tmp/main ."
# Binary file yields from `cmd`.
bin = "tmp/main"
# This is not a shell command. Some system will only use `air` command by default.
full_bin = "APP_ENV=development ./tmp/main"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "docs"]
# Exclude files.
exclude_file = []
# It's an array of regexp strings.
exclude_regexp = ["_test.go"]
# This log file places in your `tmp_dir` folder.
log = "air_errors.log"
# Watch these directories if you don't want to watch the root directory.
include_dir = []
# Exclude files from `tmp_dir`.
exclude_renderer = [""]

[log]
# Show log time
time = false

[color]
# Color error.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
